name: CI & Deploy

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with Docker Compose
        run: |
          docker compose up --build --wait tests

      - name: Build production image
        if: success()
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Example: Push to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: success()
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
